### ISSUE TITLE
LoRaWAN not working with ElectronicCats fork of arduino-lmic

### ISSUE THREAD

**Issue by beegee-tokyo** [ElectronicCats/Bast-WAN#9]
I am trying to get the BastWAN to work on LoRaWAN.
Region US915
Gateway RAK7258 (of course)
Server Chirpstack running on RPi 4

I started with the [BeeLAN library](https://github.com/BeelanMX/Beelan-LoRaWAN) and it works somehow, but it seems to be limited in functionality (`Receiving and processing MAC commands.`). In addition, I need support for AS923-3 in the future, but it is difficult to add new regions.

Next I tried your fork of [arduino-lmic](https://github.com/ElectronicCats/arduino-lmic). But it fails to join. I can see on the gateway the join requests and join accepts, but it seems the app [ttn-otaa-bastwan-us915](https://github.com/ElectronicCats/arduino-lmic/tree/master/examples/ttn-otaa-bastwan-us915) does not receive the join accept.
Gateway log:
![image](https://user-images.githubusercontent.com/512690/118250185-c3739680-b4d8-11eb-9a95-9807f7721ec6.png)
App log:
```log
Packet queued
49579: EV_JOINING
49680: EV_TXSTART
451194: EV_JOIN_TXCOMPLETE: no JoinAccept
453562: EV_TXSTART
833894: EV_JOIN_TXCOMPLETE: no JoinAccept
1134824: EV_TXSTART
1536367: EV_JOIN_TXCOMPLETE: no JoinAccept
1592096: EV_TXSTART
1972379: EV_JOIN_TXCOMPLETE: no JoinAccept
2659950: EV_TXSTART
3061508: EV_JOIN_TXCOMPLETE: no JoinAccept
3067960: EV_TXSTART
3448286: EV_JOIN_TXCOMPLETE: no JoinAccept
3782371: EV_TXSTART
4183891: EV_JOIN_TXCOMPLETE: no JoinAccept
4205018: EV_TXSTART
4585344: EV_JOIN_TXCOMPLETE: no JoinAccept
4739341: EV_TXSTART
```

Any idea?
I guess I have the pin mapping correct, because I can send.
```C++
// Pin mapping for ElectronicCats BastWAN LoRa
const lmic_pinmap lmic_pins = {
  .nss = SS,
  .rxtx = RFM_SWITCH,
  .rst = RFM_RST,
  .dio = {RFM_DIO0, RFM_DIO1, RFM_DIO2},
  .rxtx_rx_active = 0,
  .rssi_cal = 10,              // LBT cal for the Adafruit Feather M0 LoRa, in dB
  .spi_freq = 8000000,
};
```

**Comment by wero1414** [comment]
Hi! This problems seems related to the manage of the Tx/Rx inside the RAK module  i will try to get it to work for implementing the TX and Rx managing on the library

**Comment by beegee-tokyo** [comment]
@wero1414 
Hi Eduardo,
Anything I can help with?

**Comment by beegee-tokyo** [comment]
I have no idea why, but it is working now.
All I had to do was 
a) Add `Serial.printf` to the BSP
b) Enable `#define LMIC_PRINTF_TO Serial` in `config.h` in your `arduino-lmic` fork. 

Serial log:
```log
TestingPacket queued
33300: EV_JOINING
380072: EV_TXSTART
742360: EV_JOINED
netid: 0
devaddr: 13FF771
AppSKey: F3-8D-12-D2-BA-F7-19-53-F1-88-52-67-D8-90-FE-0C
NwkSKey: 52-19-52-C1-B9-A3-1F-EC-30-CA-67-47-99-76-14-E7
743002: EV_TXCOMPLETE (includes waiting for RX windows)
2618149: EV_TXSTART
Packet queued
2706196: EV_TXCOMPLETE (includes waiting for RX windows)
3903873: EV_TXSTART
3988065: EV_TXCOMPLETE (includes waiting for RX windows)
5061648: EV_TXSTART
5144593: EV_TXCOMPLETE (includes waiting for RX windows)
6091425: EV_TXSTART
6174352: EV_TXCOMPLETE (includes waiting for RX windows)
7121200: EV_TXSTART
7204184: EV_TXCOMPLETE (includes waiting for RX windows)
8150977: EV_TXSTART
8289764: EV_TXCOMPLETE (includes waiting for RX windows)
10164913: EV_TXSTART
Packet queued
10306260: EV_TXCOMPLETE (includes waiting for RX windows)
```

**Comment by sabas1080** [comment]
Hi @beegee-tokyo I have fixed some problems in the variant that solve problems in Beelan lorawan library, it may be related to the problems you have

https://github.com/ElectronicCats/ArduinoCore-samd/pull/9

**Comment by beegee-tokyo** [comment]
Didn't solve it.
I get it to join sometimes if I enable Debug output, but not always.
Without Debug output it doesn't join. 
Might be a timing problem. I see join request and join accept messages, but the accept message gets lost.

Interesting, in the cases that it joins, I can send downlink packages and they work. 

Maybe just a problem in the join RX window timings?

**Comment by Eric286** [comment]
Dear @beegee-tokyo 

Do you still require assistance with your issue or was it already resolved in another way?

Have a nice day!
Kind regards,

Support Team.

**Comment by beegee-tokyo** [comment]
Can be closed. Stopped using BastWAN. Terrible device.
